version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/storyteller

  db:
    image: postgres
    environment:
      POSTGRES_DB: storyteller
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
